### ISSUE TITLE
how to play one random sound from a folder of sounds?

### ISSUE THREAD

**Issue by defensem3ch** [parklez/twitch-bot#35]
Please help, I've been trying this all day and I've got nothing. I can either play all the sounds from a folder or none. Adding a command to core_sounds.py to just play a sound doesn't work with AudioPlayer, I don't know what I'm doing wrong. I would share my code but I've mostly just tried to copy it from yours and it's unsuccessful. An example would be like:
```
@BOT.decorator(['!random'])
def random_sound(_):
    rand = random.choice(SOUNDS)
    rand_sound = AudioPlayer(os.path.join(SOUNDS_PATH, rand))
    play_sound(rand_sound)
```
Nothing happens and I have no idea why this doesn't work... please help!!!

**Comment by parklez** [comment]
Hey there! I'm glad to have people interested in this project! 😸

The reason why it's not working is because Python's garbage collector is cleaning up the loaded sound in memory before AudioPlayer can even play it.*

A minimalistic solution is to attach the reference of that sound to the function object itself:

```python
import random
@BOT.decorator(['!random'])
def random_sound(message: Message):
    rand = random.choice(SOUNDS)
    random_sound.rand_sound = AudioPlayer(os.path.join(SOUNDS_PATH, rand))
    play_sound(random_sound.rand_sound)
```

*Excuse if I'm innacuratewith this explanation, I had this issue in the past and I recall answer being something along these lines. Another solution would be to call AudioPlayer's .play() method with `block=True`. But it would hand the entire program and we don't want that ^^

**Comment by defensem3ch** [comment]
Thank you! That was all I needed :D
